Orca integration
pacificclimate/pdp_util pull request #29
Opened 2021-03-19 22:49 UTC by cairosanders

- Replaces call to `pydap` in `RasterServer` with 301 response redirecting to `orca`
- Adds a test for the `orca` section in of the `RasterServer`

2021-03-23 17:24 UTC, nikola-rados requested changes
I have some general questions and comments but overall this looks good. Nice work!

2021-03-23 17:24 UTC, nikola-rados commented on pdp_util/raster.py
> +            orca_url = build_orca_url(self.config['handlers'], self.config['thredds_root'], req)
If we don't end up using the `path_info` below, then we can just pass in `req.query_string`.

2021-03-23 17:24 UTC, nikola-rados commented on pdp_util/raster.py
> +            return Response(status_code=301, location=orca_url)
`301` seems to make a fair amount of sense since we are calling a different service from within the `pdp`.

2021-03-23 17:24 UTC, nikola-rados commented on tests/test_raster.py
> +    assert resp.status_code == 301
We may want to consider making a test where a bad request is made and we check what `status_code` is sent back.

2021-03-24 16:09 UTC, cairosanders commented on pdp_util/raster.py
> +            break
the "handler" key in the config is where the `url` and `file` are stored which we need to build the url for orca

2021-03-24 16:37 UTC, jameshiebert commented on tests/test_raster.py
> +                        'url': 'pr+tasmin+tasmax+wind_day_CGCM3_A1B_run1_19500101-21001231.nc',
Looks like this file in particular is not:

```sql
pcic_meta=> select ensemble_name from data_files natural join data_file_variables natural join ensemble_data_file_variables natural join ensembles where filename = '/storage/data/projects/dataportal/data/vic_gen1_input/pr+tasmin+tasmax+wind_day_CGCM3_A1B_run1_19500101-21001231.nc'';
<no results>
```

Ensemble that are in use can be found here:

```bash
james@basalt:~/code/git/pdp/pdp/portals$ grep "ensemble_name =" *.py
bccaq2_downscale.py:ensemble_name = 'bccaq_version_2'
bccaq_extremes.py:ensemble_name = 'bccaq_extremes'
bc_prism.py:ensemble_name = 'bc_prism_monthly_and_climos'
downscale_archive.py:ensemble_name = 'downscaled_gcms_archive'
gridded_observations.py:ensemble_name = 'gridded-obs-met-data'
vic_gen1.py:ensemble_name = 'vic_gen1'
vic_gen2.py:ensemble_name = 'vicgl_cmip5'
```

And then you can use that to search the files that are in use for a given ensemble:

```sql
pcic_meta=> select filename from data_files natural join data_file_variables natural join ensemble_data_file_variables natural join ensembles where ensemble_name = 'gridded-obs-met-data' limit 5
pcic_meta-> ;
                                                     filename                                                      
-------------------------------------------------------------------------------------------------------------------
 /storage/data/projects/dataportal/data/vic-gen2-forcing/tasmax_forcings_new_symap_BCandCol_1950-2006_11DEC2014.nc
 /storage/data/projects/dataportal/data/vic-gen2-forcing/pr_forcings_new_symap_BCandCol_1950-2006_11DEC2014.nc
 /storage/data/projects/dataportal/data/vic-gen2-forcing/wind_forcings_new_symap_BCandCol_1950-2006_11DEC2014.nc
 /storage/data/projects/dataportal/data/vic-gen2-forcing/tasmin_forcings_new_symap_BCandCol_1950-2006_11DEC2014.nc
 /storage/data/projects/dataportal/data/vic-gen2-forcing/anusplin_pr_final.nc
(5 rows)
```

2021-03-24 17:45 UTC, nikola-rados approved these changes
This looks good to me, nice work!

2021-03-24 17:45 UTC, nikola-rados commented on pdp_util/raster.py
> +    '''
Appreciate this thank you!

2021-03-24 17:45 UTC, nikola-rados commented on tests/test_raster.py
> +        assert var in data.variables
:+1:

2021-03-24 17:45 UTC, nikola-rados commented on tests/test_raster.py
> +        assert 'Server Error' in html_content
:+1:

2021-04-30 19:24 UTC, nikola-rados approved these changes
Code looks good and the tests pass, nice job!

2021-04-30 19:28 UTC, merged